name: arm64aws_build

## self runner C++ build hosted on AWS Arm64
## see: https://github.com/marketplace/actions/build-c-project

on: [push]

jobs:
  project-build:
    runs-on: self-hosted # self-hosted runner on AWS

    steps:

    - name: CPU Architecture
      run: lscpu

    - name: Checkout XMRIGCC fork repository
      uses: actions/checkout@v2.0.0

    - name: Apt install required libraries
      run: |
        sudo apt -y update
        sudo apt -y install libuv1-dev build-essential cmake libmicrohttpd-dev libssl-dev

    # cmake_build_action options at: https://github.com/marketplace/actions/build-c-project
    - name: Build project
      uses: nicledomaS/cmake_build_action@v1.4
      with:
        cmake_args: -DWITH_HWLOC=OFF;-DCMAKE_BUILD_TYPE=Release;-DWITH_OPENCL=OFF;-DWITH_CUDA=OFF;-DWITH_ARGON2=OFF;-DXMRIG_DEPS=${{github.workspace}}/xmrig-deps/gcc/x64/include
        submodule_update: ON

    - name: Move 3 binaries into 'binaries' directory
      run: |
        mkdir ${{github.workspace}}/build/binaries
        mv ${{github.workspace}}/build/xmrig* ${{github.workspace}}/build/binaries/
        ls -la ${{github.workspace}}/build/binaries/

    - name: Upload binaries as zipped artifact
      uses: actions/upload-artifact@v1
      with:
        name: binaries
        path: ${{github.workspace}}/build/binaries


